### ISSUE TITLE
License for data.yaml

### ISSUE THREAD

**Issue by rkdarst** [nordic-rse/map#12]
Right now repo has just AGPL for the code.  We should probably have a different license for the dataset itself, depending on what we want to do.  I can't find evidence that *GPL gives rights for data mining or other things necessary for data.

Equally, what do we want this data to *not* be used for?

Also the license will probably help cover us from the personal data standpoint...

I can request a consultation and ask for advice on the topic, and how personal data + licensing relate.  What do you think?

My suggestions so far are CC-BY or CC-BY-SA for data.yaml.  The CC-BY is our standard recommendation dataset licenses, and we may be more strict because this is explicitly a community project.

**Comment by bast** [comment]
Thanks for raising this. Consultation would be very useful since I plan to use the map tech in several contexts with same legal questions. I would be equally fine both with CC-BY and CC-BY-SA.

**Comment by rkdarst** [comment]
I propose a share-alike license: the major community-driven projects tend to be that.

And my consultation gave ma relatively useful answer: since this is a *publication* and about *expression*, all of the typical GDPR problems are not here.  As makes sense, given that the whole point is to publish to the world.  We should still be as clear and transparent as possible.

I'll send a PR addressing both of these soon.

**Comment by bast** [comment]
Super! Thanks for clarifying this.
