### ISSUE TITLE
map page missing the navigation bar

### ISSUE THREAD

**Issue by eglerean** [nordic-rse/map#19]
hi

the map page does not use the same layout as https://nordic-rse.org/ and because of that it lacks the navigation bar at the top (making it impossible to "go back" to main page or other sections)

Solutions (I can help implementing them)

1) code the navigation par manually into the index.html (will need to be updated whenever the actual navigation bar is updated
2) make a reduced navigation bar just to "go back" to nordic-rse site
3) just add links to go back within the text or at the bottom

Similarly, also the footer of the page is missing and could be addedd manually to index.html.

**Comment by bast** [comment]
Another solution would be to add the `/map/` to the nordic-rse.org repo directly. My motivation for keeping this apart was that I imagined that this could be useful for other contexts but maybe that is trying to be too general for a use case that never arrives.

**Comment by bast** [comment]
I think I like 2 best.

**Comment by eglerean** [comment]
One could have an "iframe" that loads the external map while keeping the navigation bar. It's a bit of a early 2000s solution maybe, not sure how well it plays with mobile devices...

Maybe I can work on #2 as a quick fix, and then we can embed map under /map/ in the long run?

**Comment by bast** [comment]
Good idea. I will also think about how we can embed without duplicating code too much.

**Comment by bast** [comment]
This is now embedded directly in the page by https://github.com/nordic-rse/nordic-rse.github.io/pull/289
